apache:
    build: docker-containers/apache
    volumes:
        - ./:/var/www/html
    ports:
        - 7001:80
    links:
        - mysql
mysql:
    image: mysql:5.7
    ports:
        - 7003:3306
    environment:
            - MYSQL_ROOT_PASSWORD=my-secret-pw
            - MYSQL_DATABASE=sf-php-demo-app