# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.repository.car:
        class: AppBundle\Repository\Car
        factory: ["@doctrine.orm.default_entity_manager", "getRepository"]
        arguments:
            - AppBundle:Car
    app.repository.lengthUnit:
            class: Doctrine\ORM\EntityRepository
            factory: ["@doctrine.orm.default_entity_manager", "getRepository"]
            arguments:
                - AppBundle\Entity\LengthUnit
    app.repository.car_entry:
            class: AppBundle\Repository\CarEntry
            factory: ["@doctrine.orm.default_entity_manager", "getRepository"]
            arguments:
                - AppBundle:CarEntry
    app.repository.car_action:
                class: AppBundle\Repository\CarAction
                factory: ["@doctrine.orm.default_entity_manager", "getRepository"]
                arguments:
                    - AppBundle:CarAction
    app.service.car:
        class: AppBundle\Service\Car
        arguments:
            - '@app.repository.car'
            - '@app.repository.car_entry'
            - '@app.repository.car_action'